### ISSUE TITLE
Add-CVClient missing in Commvault.CommCell

### ISSUE THREAD

**Issue by joaval** [CommvaultEngg/CVPowershellSDK#1]
Have downloaded this and installed with "Install-CVModules.ps1"
Trying to add a new client (VM) to my CommCell.
But function Add-CVClient is missing.

E:\Admin\CVPowershellSDK-master
PS > Get-Command -Noun CVClient
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-CVClient                                       2.0.9      Commvault.CommCell
Function        Set-CVClient                                       2.0.9      Commvault.CommCell

**Comment by gstoops** [comment]
Hi joaval, this is on my TODO list. Please share any specifics of what type of client you would like to be able to add; e.g. virtual server hypervisor etc.

Thanks

**Comment by joaval** [comment]
Hi,
I wanted to install 3 agents (File System, SQL Server, Virtual Server) and register the client in Commcell.This during our automated database services where we provision new VMs with SQL Server.
Have now solved it by:
- creating a CustomPackage from the Media Kit with the 3 agents
- downloading the CustomPackage zip-file to the client VM
- running silent install with a generated XML file as input
This solves my problem.
So now I don't need a Powershell function for this part.
