### ISSUE TITLE
API Limit when querying jobs, way to update the limit?

### ISSUE THREAD

**Issue by bogski87** [CommvaultEngg/CVPowershellSDK#11]
Hello,

I'm using the Commvault script from here and have a question. I've discovered recently that the Commvault API is limited to 100 results per request. 

![image](https://user-images.githubusercontent.com/35738951/76536833-c5753c00-6474-11ea-82fb-180bffa4e5c8.png)

I'm tempted to add the limit part to the end of the endpoint section in the Commvault/RESTSession.psm1 file
![image](https://user-images.githubusercontent.com/35738951/76536979-feadac00-6474-11ea-8d53-c23b5cce828c.png)

I'm not sure if i should set this as empty or 0 for unlimited or whether i should set it to something ridiculous like 9999, or if this is the right place to edit it :)

Any ideas?

Regards
Phil

**Comment by JnaneshD05** [comment]
We can have a parameter to the command as limit with default value 100 . I will check this and implement
