### ISSUE TITLE
NuGet required

### ISSUE THREAD

**Issue by vollraths** [CommvaultEngg/CVPowershellSDK#2]
Installation-Script tries to download NuGet, such behavior is usually blocked in Enterprise Environments, where no Internet-Access is granted at all or permitted Sites are highly restricted.

WARNING: MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet  provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or 'C:\Users\xxx\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by
running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'.

**Comment by gstoops** [comment]
Hi vollraths, this issue has been addressed in the latest push of .\Install-CVModules.ps1. New command line switches -Offline and -PersistModulePath and parameter -Scope AllUsers/CurrentUser allow customized install in a restricted enterprise environment.
