### ISSUE TITLE
Get-CVVirtualMachine: no virtual machines found after Update to Version 11 SP26.27

### ISSUE THREAD

**Issue by MichaelBuehlmeier** [CommvaultEngg/CVPowershellSDK#36]
After updating to Version 11 SP26.27 due to issues with Oracle command "Get-CVVirtualMachine"  does not work anymore
_Get-CVVirtualMachine: no virtual machines found_

**Comment by JnaneshD05** [comment]
Hi @MichaelBuehlmeier,  Please paste the log lines from WebServer.log and the command output .
